package com.ultracore.difficulty;

public enum ChanceTypes {
    ARMOR_LEATHER, ARMOR_IRON, ARMOR_DIAMOND,
    SWORD_WOOD, SWORD_STONE, SWORD_IRON, SWORD_DIAMOND,

    EFFECT_STRENGTH_1, EFFECT_STRENGTH_2,

    BOW_ENCHANT_POWER_1, BOW_ENCHANT_POWER_2, BOW_ENCHANT_POWER_3, BOW_ENCHANT_POWER_4,
    BOW_ENCHANT_KNOCKBACK_1, BOW_ENCHANT_KNOCKBACK_2,
}
